// <auto-generated />
using System;
using CardPile.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardPile.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20221206103756_CardPileDB")]
    partial class CardPileDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardPile.Domain.Entities.Card", b =>
                {
                    b.Property<long>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CardID"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeckListID")
                        .HasColumnType("bigint");

                    b.HasKey("CardID");

                    b.HasIndex("DeckListID");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("CardPile.Domain.Entities.DeckList", b =>
                {
                    b.Property<long>("DeckListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeckListID"));

                    b.Property<string>("DeckListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckListID");

                    b.ToTable("DeckList", (string)null);
                });

            modelBuilder.Entity("CardPile.Domain.Entities.Card", b =>
                {
                    b.HasOne("CardPile.Domain.Entities.DeckList", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckListID");
                });

            modelBuilder.Entity("CardPile.Domain.Entities.DeckList", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
